services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_HOST}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:8080"
    environment:
      - DB_HOST=db
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - db

volumes:
  data:

networks:
  network: