FROM python:3.12-slim-bookworm

# Install dependencies including entr
RUN apt-get update && \
    apt-get install -y --no-install-recommends entr && \
    pip install pytest && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


COPY --from=ghcr.io/astral-sh/uv:0.5.4 /uv /uvx /bin/

WORKDIR /app

COPY ./pyproject.toml ./pyproject.toml
COPY ./uv.lock ./uv.lock
RUN uv sync --dev --locked

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/src"

COPY ./src ./src
COPY ./tests ./tests

EXPOSE 4001

CMD ["uvicorn", "src.main:app", "--log-level", "debug", "--host", "0.0.0.0", "--port", "8080", "--reload"]