services:
  web:
    container_name: aklatan-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:8080"
    volumes:
      - ./src:/app/src
  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: >
      sh -c "while true; do
        find /app/tests /app/src -type f -name '*.py' | entr -n -d pytest;
      done"