services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:8080"
    environment:
      DB_HOST: db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network
    volumes:
      - ./src:/app/src
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: >
      sh -c "pytest;
        while true; do
          inotifywait -r -e modify,create,delete --include '\.py$' /app/src /app/tests;
          pytest;
        done"

volumes:
  data:

networks:
  network: