name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env file from GitHub secret
      run: echo "${{ secrets.DOTENV_FILE }}" > .env
        
    - name: Build the Docker image
      run: docker build -t yzkl/aklatan -f Dockerfile.dev .

    - name: Run tests
      run: docker run --env-file .env -e CI=true yzkl/aklatan pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # ensures build/tests succeed first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install EB CLI
        run: pip install awsebcli

      - name: Deploy to Elastic Beanstalk
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*" "*__pycache__*"
          eb init "$EB_APP_NAME" --region ${{ secrets.AWS_REGION }} --platform "Docker"
          eb use "$EB_ENV_NAME"
          eb deploy
        env:
          EB_APP_NAME: aklatan
          EB_ENV_NAME: Aklatan-env
