name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env file from GitHub secret
      run: echo "${{ secrets.DOTENV_FILE }}" > .env
        
    - name: Build the Docker image
      run: docker compose -f docker-compose.dev.yaml up --build
